export const CHIRP_CREATE_REQUEST = "CHIRP_CREATE_REQUEST";
export const CHIRP_CREATE_SUCCESS = "CHIRP_CREATE_SUCCESS";
export const CHIRP_CREATE_FAILURE = "CHIRP_CREATE_REQUEST";

export const CHIRP_DELETE_REQUEST = "CHIRP_DELETE_REQUEST";
export const CHIRP_DELETE_SUCCESS = "CHIRP_DELETE_SUCCESS";
export const CHIRP_DELETE_FAILURE = "CHIRP_DELETE_REQUEST";

export const GET_ALL_CHIRPS_REQUEST = "GET_ALL_CHIRPS_REQUEST";
export const GET_ALL_CHIRPS_SUCCESS = "GET_ALL_CHIRPS_SUCCESS";
export const GET_ALL_CHIRPS_FAILURE = "GET_ALL_CHIRPS_REQUEST";

export const GET_USERS_CHIRP_REQUEST = "GET_USERS_CHIRP_REQUEST";
export const GET_USERS_CHIRP_SUCCESS = "GET_USERS_CHIRP_SUCCESS";
export const GET_USERS_CHIRP_FAILURE = "GET_USERS_CHIRP_REQUEST";

export const USER_LIKE_CHIRP_REQUEST = "USER_LIKE_CHIRP_REQUEST";
export const USER_LIKE_CHIRP_SUCCESS = "USER_LIKE_CHIRP_SUCCESS";
export const USER_LIKE_CHIRP_FAILURE = "USER_LIKE_CHIRP_REQUEST";

export const LIKE_CHIRP_REQUEST = "LIKE_CHIRP_REQUEST";
export const LIKE_CHIRP_SUCCESS = "LIKE_CHIRP_SUCCESS";
export const LIKE_CHIRP_FAILURE = "LIKE_CHIRP_REQUEST";

export const FIND_CHIRP_BY_ID_REQUEST = "FIND_CHIRP_BY_ID_REQUEST";
export const FIND_CHIRP_BY_ID_SUCCESS = "FIND_CHIRP_BY_ID_SUCCESS";
export const FIND_CHIRP_BY_ID_FAILURE = "FIND_CHIRP_BY_ID_REQUEST";

export const REPLY_CHIRP_REQUEST = "REPLY_CHIRP_REQUEST";
export const REPLY_CHIRP_SUCCESS = "REPLY_CHIRP_SUCCESS";
export const REPLY_CHIRP_FAILURE = "REPLY_CHIRP_REQUEST";

export const RECHIRP_REQUEST = "RECHIRP_REQUEST";
export const RECHIRP_SUCCESS = "RECHIRP_SUCCESS";
export const RECHIRP_FAILURE = "RECHIRP_REQUEST";